import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'package:intl/intl.dart';
import 'package:share_plus/share_plus.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../providers/auth_provider.dart';
import '../services/panic_history_service.dart';
import '../services/vibration_service.dart';
import 'panic_event_detail_screen.dart';

class EnhancedPanicHistoryScreen extends StatefulWidget {
  const EnhancedPanicHistoryScreen({super.key});

  @override
  State<EnhancedPanicHistoryScreen> createState() => _EnhancedPanicHistoryScreenState();
}

class _EnhancedPanicHistoryScreenState extends State<EnhancedPanicHistoryScreen> {
  final PanicHistoryService _historyService = PanicHistoryService();
  final VibrationService _vibrationService = VibrationService();

  List<Map<String, dynamic>> _events = [];
  Map<String, dynamic>? _statistics;
  bool _isLoading = true;
  String _filterMode = 'all'; // all, thisWeek, thisMonth

  @override
  void initState() {
    super.initState();
    _loadHistory();
  }

  Future<void> _loadHistory() async {
    setState(() => _isLoading = true);

    final authProvider = Provider.of<AuthProvider>(context, listen: false);
    final userId = authProvider.user?.uid;

    if (userId != null) {
      final events = await _historyService.getPanicHistory(userId);
      final stats = await _historyService.getPanicStatistics(userId);

      if (mounted) {
        setState(() {
          _events = events;
          _statistics = stats;
          _isLoading = false;
        });
      }
    } else {
      setState(() => _isLoading = false);
    }
  }

  List<Map<String, dynamic>> get _filteredEvents {
    final now = DateTime.now();

    switch (_filterMode) {
      case 'thisWeek':
        return _events.where((e) {
          final timestamp = (e['timestamp'] as Timestamp).toDate();
          final diff = now.difference(timestamp).inDays;
          return diff <= 7;
        }).toList();

      case 'thisMonth':
        return _events.where((e) {
          final timestamp = (e['timestamp'] as Timestamp).toDate();
          return timestamp.year == now.year && timestamp.month == now.month;
        }).toList();

      default:
        return _events;
    }
  }

  Future<void> _exportHistory() async {
    await _vibrationService.light();

    final authProvider = Provider.of<AuthProvider>(context, listen: false);
    final userName = authProvider.user?.displayName ?? 'User';

    final report = StringBuffer();
    report.writeln(' AKEL PANIC HISTORY REPORT');
    report.writeln('User: $userName');
    report.writeln('Generated: ${DateFormat('MMM dd, yyyy - hh:mm a').format(DateTime.now())}');
    report.writeln('Total Events: ${_events.length}');
    report.writeln('');
    report.writeln('═══════════════════════════════════');
    report.writeln('');

    for (var event in _events) {
      final timestamp = (event['timestamp'] as Timestamp).toDate();
      final dateStr = DateFormat('MMM dd, yyyy - hh:mm a').format(timestamp);

      report.writeln(' $dateStr');
      report.writeln('Mode: ${event['silentMode'] == true ? 'Silent' : 'Normal'}');
      report.writeln('Contacts: ${event['contactsNotified'] ?? 0}');
      if (event['latitude'] != null && event['longitude'] != null) {
        report.writeln('Location: ${event['latitude']}, ${event['longitude']}');
      }
      report.writeln('');
    }

    report.writeln('═══════════════════════════════════');
    report.writeln('Generated by AKEL Panic Button');

    await Share.share(report.toString(), subject: 'AKEL Panic History Report');
  }

  Future<void> _confirmClearHistory() async {
    await _vibrationService.warning();

    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Row(
          children: [
            Icon(Icons.warning, color: Colors.red),
            SizedBox(width: 12),
            Text('Clear All History?'),
          ],
        ),
        content: const Text(
          'This will permanently delete all panic event records.\n\n'
              'This action cannot be undone.',
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: const Text('Cancel'),
          ),
          ElevatedButton(
            onPressed: () => Navigator.pop(context, true),
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.red,
              foregroundColor: Colors.white,
            ),
            child: const Text('Clear All'),
          ),
        ],
      ),
    );

    if (confirmed == true && mounted) {
      final authProvider = Provider.of<AuthProvider>(context, listen: false);
      final userId = authProvider.user?.uid;

      if (userId != null) {
        final success = await _historyService.clearAllHistory(userId);

        if (mounted) {
          if (success) {
            await _vibrationService.success();
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text(' All history cleared'),
                backgroundColor: Colors.green,
              ),
            );
            _loadHistory();
          } else {
            await _vibrationService.error();
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text(' Failed to clear history'),
                backgroundColor: Colors.red,
              ),
            );
          }
        }
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Panic History'),
        actions: [
          if (_events.isNotEmpty) ...[
            IconButton(
              icon: const Icon(Icons.ios_share),
              tooltip: 'Export History',
              onPressed: _exportHistory,
            ),
            IconButton(
              icon: const Icon(Icons.delete_forever),
              tooltip: 'Clear All',
              onPressed: _confirmClearHistory,
            ),
          ],
        ],
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : _events.isEmpty
          ? _buildEmptyState()
          : Column(
        children: [
          _buildStatisticsCard(),
          _buildFilterChips(),
          Expanded(child: _buildEventsList()),
        ],
      ),
    );
  }

  Widget _buildEmptyState() {
    return Center(
      child: Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Icon(
            Icons.history,
            size: 80,
            color: Colors.grey[400],
          ),
          const SizedBox(height: 16),
          Text(
            'No Panic Events',
            style: TextStyle(
              fontSize: 20,
              fontWeight: FontWeight.bold,
              color: Colors.grey[600],
            ),
          ),
          const SizedBox(height: 8),
          Text(
            'Your panic alert history will appear here',
            style: TextStyle(
              color: Colors.grey[500],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildStatisticsCard() {
    if (_statistics == null) return const SizedBox.shrink();

    return Container(
      margin: const EdgeInsets.all(16),
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          colors: [
            Theme.of(context).primaryColor,
            Theme.of(context).primaryColor.withValues(alpha: 0.7),
          ],
        ),
        borderRadius: BorderRadius.circular(16),
        boxShadow: [
          BoxShadow(
            color: Theme.of(context).primaryColor.withValues(alpha: 0.3),
            blurRadius: 20,
            offset: const Offset(0, 10),
          ),
        ],
      ),
      child: Column(
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            children: [
              _buildStatItem(
                'Total',
                '${_statistics!['totalEvents']}',
                Icons.warning,
              ),
              _buildStatItem(
                'This Week',
                '${_statistics!['thisWeek']}',
                Icons.calendar_today,
              ),
              _buildStatItem(
                'This Month',
                '${_statistics!['thisMonth']}',
                Icons.calendar_month,
              ),
            ],
          ),
          const SizedBox(height: 16),
          const Divider(color: Colors.white24),
          const SizedBox(height: 16),
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceAround,
            children: [
              _buildStatItem(
                'Peak Hour',
                '${_statistics!['mostCommonHour']}:00',
                Icons.access_time,
              ),
              _buildStatItem(
                'Silent Mode',
                '${_statistics!['silentModeUsage']}%',
                Icons.notifications_off,
              ),
            ],
          ),
        ],
      ),
    );
  }

  Widget _buildStatItem(String label, String value, IconData icon) {
    return Column(
      children: [
        Icon(icon, color: Colors.white, size: 24),
        const SizedBox(height: 8),
        Text(
          value,
          style: const TextStyle(
            color: Colors.white,
            fontSize: 20,
            fontWeight: FontWeight.bold,
          ),
        ),
        const SizedBox(height: 4),
        Text(
          label,
          style: const TextStyle(
            color: Colors.white70,
            fontSize: 12,
          ),
        ),
      ],
    );
  }

  Widget _buildFilterChips() {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 16),
      child: Row(
        children: [
          _buildFilterChip('All', 'all'),
          const SizedBox(width: 8),
          _buildFilterChip('This Week', 'thisWeek'),
          const SizedBox(width: 8),
          _buildFilterChip('This Month', 'thisMonth'),
        ],
      ),
    );
  }

  Widget _buildFilterChip(String label, String mode) {
    final isSelected = _filterMode == mode;

    return FilterChip(
      label: Text(label),
      selected: isSelected,
      onSelected: (selected) {
        _vibrationService.light();
        setState(() => _filterMode = mode);
      },
      backgroundColor: Colors.transparent,
      selectedColor: Theme.of(context).primaryColor.withValues(alpha: 0.2),
      checkmarkColor: Theme.of(context).primaryColor,
      labelStyle: TextStyle(
        color: isSelected
            ? Theme.of(context).primaryColor
            : Theme.of(context).textTheme.bodyLarge?.color,
        fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
      ),
    );
  }

  Widget _buildEventsList() {
    final filtered = _filteredEvents;

    if (filtered.isEmpty) {
      return Center(
        child: Text(
          'No events for this filter',
          style: TextStyle(color: Colors.grey[500]),
        ),
      );
    }

    return ListView.builder(
      padding: const EdgeInsets.all(16),
      itemCount: filtered.length,
      itemBuilder: (context, index) {
        final event = filtered[index];
        return _buildEventCard(event);
      },
    );
  }

  Widget _buildEventCard(Map<String, dynamic> event) {
    final timestamp = (event['timestamp'] as Timestamp).toDate();
    final dateStr = DateFormat('MMM dd, yyyy').format(timestamp);
    final timeStr = DateFormat('hh:mm a').format(timestamp);
    final isSilent = event['silentMode'] == true;

    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      child: InkWell(
        onTap: () async {
          await _vibrationService.light();
          if (mounted) {
            Navigator.push(
              context,
              MaterialPageRoute(
                builder: (_) => PanicEventDetailScreen(event: event),
              ),
            );
          }
        },
        borderRadius: BorderRadius.circular(12),
        child: Padding(
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Container(
                    padding: const EdgeInsets.all(8),
                    decoration: BoxDecoration(
                      color: isSilent
                          ? Colors.purple.withValues(alpha: 0.1)
                          : Colors.red.withValues(alpha: 0.1),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Icon(
                      isSilent ? Icons.notifications_off : Icons.warning,
                      color: isSilent ? Colors.purple : Colors.red,
                      size: 24,
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text(
                          isSilent ? 'Silent Alert' : 'Panic Alert',
                          style: const TextStyle(
                            fontWeight: FontWeight.bold,
                            fontSize: 16,
                          ),
                        ),
                        const SizedBox(height: 4),
                        Row(
                          children: [
                            Icon(
                              Icons.calendar_today,
                              size: 12,
                              color: Colors.grey[600],
                            ),
                            const SizedBox(width: 4),
                            Text(
                              '$dateStr • $timeStr',
                              style: TextStyle(
                                fontSize: 12,
                                color: Colors.grey[600],
                              ),
                            ),
                          ],
                        ),
                      ],
                    ),
                  ),
                  const Icon(Icons.chevron_right, color: Colors.grey),
                ],
              ),
              const SizedBox(height: 12),
              Row(
                children: [
                  _buildInfoChip(
                    Icons.people,
                    '${event['contactsNotified'] ?? 0} contacts',
                    Colors.blue,
                  ),
                  const SizedBox(width: 8),
                  if (event['locationTrackingActive'] == true)
                    _buildInfoChip(
                      Icons.route,
                      'Trail',
                      Colors.green,
                    ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildInfoChip(IconData icon, String label, Color color) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      decoration: BoxDecoration(
        color: color.withValues(alpha: 0.1),
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: color.withValues(alpha: 0.3)),
      ),
      child: Row(
        mainAxisSize: MainAxisSize.min,
        children: [
          Icon(icon, size: 12, color: color),
          const SizedBox(width: 4),
          Text(
            label,
            style: TextStyle(
              fontSize: 11,
              color: color,
              fontWeight: FontWeight.bold,
            ),
          ),
        ],
      ),
    );
  }
}